// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Case struct {
	ID           string `json:"id"`
	Province     string `json:"province"`
	Gender       string `json:"gender"`
	Neighborhood string `json:"neighborhood"`
	Age          int    `json:"age"`
	Stage        string `json:"stage"`
	Dead         string `json:"dead"`
}

type CaseSearch struct {
	Province     *string `json:"province"`
	Age          *int    `json:"age"`
	Stage        *string `json:"stage"`
	Dead         *string `json:"dead"`
	Neighborhood *string `json:"neighborhood"`
	Gender       *string `json:"gender"`
}
