// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CaseSearch struct {
	Province     *string `json:"province"`
	Age          *int    `json:"age"`
	Stage        *string `json:"stage"`
	Dead         *string `json:"dead"`
	Neighborhood *string `json:"neighborhood"`
	Gender       *string `json:"gender"`
}
